name: Main branch checks

on:
  push:
    branches:
      - main
      - "v*.*.*"
    tags:
      - "v*.*.*"

jobs:
  python:
    uses: ./.github/workflows/python-checks.yml
  typescript:
    uses: ./.github/workflows/typescript-checks.yml
