name: Integ Tests

on:
  workflow_dispatch: {}

jobs:
  integ_tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: "Set up Typescript"
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "src/python/.python-version"

      - name: Install CDK CLI
        run: npm install -g aws-cdk

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.INTEG_TEST_ROLE_ARN }}
          aws-region: ${{ secrets.INTEG_TEST_REGION }}

      - name: Run tests
        run: |
          cd src/python
          uv venv
          source .venv/bin/activate
          cd ../..
          ./e2e_tests/run_integ_test.sh
        timeout-minutes: 15
        working-directory: ${{ github.workspace }}

      - name: Clean up
        if: always()
        run: |
          source src/python/.venv/bin/activate
          ./e2e_tests/clean_up_integ_test.sh
        working-directory: ${{ github.workspace }}
