name: Pull request checks

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]
    branches: [main]

jobs:
  python:
    uses: ./.github/workflows/python-checks.yml
  typescript:
    uses: ./.github/workflows/typescript-checks.yml
  cdk:
    uses: ./.github/workflows/cdk-checks.yml
  integ-test:
    if: contains(github.event.pull_request.labels.*.name, 'safe-to-test')
    uses: ./.github/workflows/integ-tests.yml
