name: Typescript Checks

on:
  workflow_call:

jobs:
  check_typscript:
    name: Check Typescript library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Set up Typescript"
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci
        working-directory: ./src/typescript

      - name: Build
        run: npm run build
        working-directory: ./src/typescript

      - name: Test
        run: npm test
        working-directory: ./src/typescript

      - name: Lint
        run: npm run lint
        working-directory: ./src/typescript
