name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  python:
    permissions:
      contents: read
    uses: ./.github/workflows/python-checks.yml
  typescript:
    permissions:
      contents: read
    uses: ./.github/workflows/typescript-checks.yml
  cdk:
    permissions:
      contents: read
    uses: ./.github/workflows/cdk-checks.yml
